name: Deploy to AWS S3

on:
  push:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
           node-version: ${{ matrix.node-version }}
           cache: 'npm'
      - run: npm ci
      
      - run: |
          touch config.js
          echo "${{ secrets.CONFIG_ENV_FILE }}" > config.js
      - run: npm run build

      - name: Upload File to AWS S3
        uses: ramonpaolo/action-upload-s3@main
        with:
         AWS_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET }}
         AWS_REGION: us-east-2
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

         # path of local file to upload
         local_path_upload: ./

        
         # want to zip file/folder before send to S3
         zip: true
        
         # the name of key/object to store in S3
         name_to_save_on_s3: "release"

                                                
       
