name: Deploy Images to GHCR

on: workflow_dispatch
  #push:
    #branches:
      #- main
  #workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.MY_TOKEN}}
          - run: |
              touch .env.local 
              echo "${{ secrets.ENV_FILE }}" > .env.local

          - name: Build and push the Docker image
            uses: docker/build-push-action@v5
            with:
                context: .
                push: true
                tags: |
                  ghcr.io/andriiyurov/next-blog:latest
                  ghcr.io/andriiyurov/next-blog:${{ github.sha }}

          - name: Upload to S3
            uses: jakejarvis/s3-sync-action@master
            with:
                args: .
            env:
                #SOURCE_DIR: ./docker/ghcr.io/andriiyurov/next-blog:latest
                AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

